// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT65kGdillItW4J6eiJGO2XBHtMoaCZPI',
    appId: '1:1040604959274:web:ba1d3fd80c912fa1952953',
    messagingSenderId: '1040604959274',
    projectId: 'instaclinics-beace',
    authDomain: 'instaclinics-beace.firebaseapp.com',
    storageBucket: 'instaclinics-beace.firebasestorage.app',
    measurementId: 'G-0G91XQHSRL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7wXrSyUNKS7tSrKqy3Vnj2uSAsqW6ojE',
    appId: '1:1040604959274:android:9077e92fcf16eeca952953',
    messagingSenderId: '1040604959274',
    projectId: 'instaclinics-beace',
    storageBucket: 'instaclinics-beace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKnDf1JDVZAwPftOursl4jh_suyh1V6BI',
    appId: '1:1040604959274:ios:af8620ced852879c952953',
    messagingSenderId: '1040604959274',
    projectId: 'instaclinics-beace',
    storageBucket: 'instaclinics-beace.firebasestorage.app',
    iosClientId: '1040604959274-4516mviqitt65g072ohqi6kesht292n3.apps.googleusercontent.com',
    iosBundleId: 'com.freshhealth.instaclinic',
  );
}
